function NewStimInit
% NewStimInit. Add NewStim3 folders to the path, sets globals and runs NewStimConfiguration
%
% 200X, Steve Van Hooser
% 2009-2025, Alexander Heimel
 
pwd = fileparts(mfilename("fullpath"));

addpath(pwd,...
fullfile(pwd,'Scripts'),...
fullfile(pwd, 'NewStimProcs'),...
fullfile(pwd, 'NewStimDisplayProcs'),...
fullfile(pwd, 'NewStimServices'),...
fullfile(pwd, 'NewStimUtilities'),...
fullfile(pwd, 'NewStimUtilities' , 'NewStimConfigureInterviewHelpers'),...
fullfile(pwd, 'NewStimServices' , 'StimScreen'),...
fullfile(pwd, 'NewStimServices' , 'MonitorScreen'),...
fullfile(pwd, 'NewStimServices' , 'GammaCorrectionTable'),...
fullfile(pwd, 'NewStimServices' , 'StimTrigger'),...
fullfile(pwd, 'NewStimServices' , 'FitzTrig'),...
fullfile(pwd, 'NewStimServices' , 'VHTrig'),...
fullfile(pwd, 'NewStimServices' , 'GaiaTrig'),...
fullfile(pwd, 'NewStimServices' , 'DaneelTrig'),...
fullfile(pwd, 'NewStimServices' , 'StimSerial'),...
fullfile(pwd, 'NewStimServices' , 'StimPCIDIO96'),...
fullfile(pwd, 'NewStimServices' , 'StimScreenBlender'),...
fullfile(pwd, 'NewStimEditor'),...
fullfile(pwd, 'RemoteCommunication'),...
fullfile(pwd, 'Stimuli'),...
fullfile(pwd, 'Stimuli' , 'Display objs'),...
fullfile(pwd, 'Stimuli' , 'CustomProcs'),...
fullfile(pwd, 'NewStimTestProcs'),...
fullfile(pwd, 'RunExperiment'),...
fullfile(pwd, 'RunExperiment' , 'usefulcalls'),...
fullfile(pwd, 'RunExperiment','panelcallbacks'),...
fullfile(pwd, 'ReceptiveFieldMapper'),...
fullfile(pwd, 'Configuration'),...
fullfile(pwd, 'Calibration'),...    % some calibration files for the packages that depend on each computer
fullfile(pwd, 'Calibration','Monitors'));

NewStimGlobals;
NewStimStimList = {};
NewStimStimScriptList = {};

if ~exist('load_invivotools','file')
    warning('Make sure that InVivoTools is installed and in the path. Essential functions might be missing otherwise.')
end

if exist('NewStimConfiguration','file')
    NewStimConfiguration;
end

if isempty(which('NewStimConfiguration')) || ~VerifyNewStimConfiguration 
    template_configuration_file = which('NewStimConfiguration_analysiscomputer');
    if isempty(template_configuration_file)
        logmsg('Could not find NewStimConfiguration_analysiscomputer.m. Please locate and containing folder to the path.');
        return
    end
	copyfile(template_configuration_file,fullfile(pwd,'Configuration','NewStimConfiguration.m'));
	warning(['No NewStimConfiguration.m file was detected;' ...
			' the program is now copying the default settings for a basic analysis computer. ' ...
			'If you need to use this computer to control stimulus computers, or if this itself ' ...
			'should be a stimulus computer, you will need to edit the file NewStimConfiguration.m ' ...
			'according to the instructions on the website.  If you want to use this computer for ' ...
			'analysis only, then no action is needed, you should be all set.']);
	zz = which('NewStimConfiguration'); % force it to look again
	eval('NewStimConfiguration;');
end

eval('NewStimObjectInit');

